"""empty message

Revision ID: 724d5e1b1553
Revises: c7d2bc9b6f7f
Create Date: 2022-05-14 12:48:45.220490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724d5e1b1553'
down_revision = 'c7d2bc9b6f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemsInCart', sa.Column('count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemsInCart', 'count')
    # ### end Alembic commands ###
